development:
  adapter: mysql2
  database: iamnii_dev
  encoding: utf8
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: iamnii_test
  encoding: utf8
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

production:
  adapter: postgresql
  database: iamnii_prod
  encoding: utf8
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

